--
-- PostgreSQL database dump
--

\restrict LQe4KSNQmZ8kW9G3agbm0S86oCROfcVbpYekolNPhAm876jL2oDGlvFkBgQb4W2

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: resurs; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA resurs;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bank_resurs_at_creditdata; Type: TABLE; Schema: resurs; Owner: -
--

CREATE TABLE resurs.bank_resurs_at_creditdata (
    id bigint NOT NULL,
    credit_id character varying(10) NOT NULL,
    bank_mfo integer NOT NULL,
    bank_name character varying(150) NOT NULL,
    loan_person_name character varying(150) NOT NULL,
    loan_pnfl character varying(14) NOT NULL,
    pas_series_number character varying(9) NOT NULL,
    tin integer NOT NULL,
    region character varying(150) NOT NULL,
    district character varying(150) NOT NULL,
    address character varying(150) NOT NULL,
    date_of_contract character varying(10) NOT NULL,
    loan_allocated_date date NOT NULL,
    contract_end_date date NOT NULL,
    contract_number character varying(10) NOT NULL,
    contract_summ character varying(20) NOT NULL,
    disbursed_loan_amount character varying(20) NOT NULL,
    loan_interest_rate character varying(20) NOT NULL,
    credit_balance character varying(20) NOT NULL,
    paid_precent_amount character varying(20) NOT NULL,
    cadastral_number character varying(30) NOT NULL,
    type_of_supply character varying(150) NOT NULL,
    credit_provision_amount character varying(150) NOT NULL,
    tin_of_company character varying(9) NOT NULL,
    name_of_company character varying(150) NOT NULL,
    type_of_credit character varying(150) NOT NULL
);


--
-- Name: bank_resurs_at_creditdata_id_seq; Type: SEQUENCE; Schema: resurs; Owner: -
--

ALTER TABLE resurs.bank_resurs_at_creditdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resurs.bank_resurs_at_creditdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_resurs_at_paymentqueue; Type: TABLE; Schema: resurs; Owner: -
--

CREATE TABLE resurs.bank_resurs_at_paymentqueue (
    id bigint NOT NULL,
    credit_id character varying(20) NOT NULL,
    paid_amount character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    sent boolean NOT NULL
);


--
-- Name: bank_resurs_at_paymentqueue_id_seq; Type: SEQUENCE; Schema: resurs; Owner: -
--

ALTER TABLE resurs.bank_resurs_at_paymentqueue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resurs.bank_resurs_at_paymentqueue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_resurs_at_paymentrequestlog; Type: TABLE; Schema: resurs; Owner: -
--

CREATE TABLE resurs.bank_resurs_at_paymentrequestlog (
    id bigint NOT NULL,
    credit_id character varying(20) NOT NULL,
    paid_amount character varying(20) NOT NULL,
    response_data jsonb NOT NULL,
    status integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: bank_resurs_at_paymentrequestlog_id_seq; Type: SEQUENCE; Schema: resurs; Owner: -
--

ALTER TABLE resurs.bank_resurs_at_paymentrequestlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resurs.bank_resurs_at_paymentrequestlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_resurs_at_resursrequestlog; Type: TABLE; Schema: resurs; Owner: -
--

CREATE TABLE resurs.bank_resurs_at_resursrequestlog (
    id bigint NOT NULL,
    credit_id character varying(20) NOT NULL,
    pnfl character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: bank_resurs_at_resursrequestlog_id_seq; Type: SEQUENCE; Schema: resurs; Owner: -
--

ALTER TABLE resurs.bank_resurs_at_resursrequestlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resurs.bank_resurs_at_resursrequestlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bank_resurs_at_creditdata; Type: TABLE DATA; Schema: resurs; Owner: -
--

COPY resurs.bank_resurs_at_creditdata (id, credit_id, bank_mfo, bank_name, loan_person_name, loan_pnfl, pas_series_number, tin, region, district, address, date_of_contract, loan_allocated_date, contract_end_date, contract_number, contract_summ, disbursed_loan_amount, loan_interest_rate, credit_balance, paid_precent_amount, cadastral_number, type_of_supply, credit_provision_amount, tin_of_company, name_of_company, type_of_credit) FROM stdin;
5	1005	1037	IPOTEKA BANK	ISMOILOV JAMSHID	52345678910111	AD2222222	222333444	BUXORO	KOGON	TEST 5	2020	2020-05-01	2025-05-01	CN005	100000000	100000000	20%	55998770	40000000	10:12:05	uy	120000000	305685255	BUXORO QURILISH	IPOTEKA
2	1002	1037	IPOTEKA BANK	KARIMOVA NILUFAR	22345678910111	AD7654321	987654321	SAMARQAND	URUT	TEST 2	2022	2022-02-01	2025-02-01	CN002	200000000	200000000	18%	104850000	50000000	10:12:02	uy	220000000	305685253	SAM QURILISH	IPOTEKA
4	1004	1037	IPOTEKA BANK	SADIYEVA SHAXNOZA	41007900231668	AD1140221	565369774	TOSHKENT	YANGIXAYOT	TEST 4	2022	2022-12-28	2023-12-19	171	334340000	334340000	17%	331086944	1380000	10:12:02:01	uy	415108680	305685252	UZSHAHAR QURILISH	KVARTIRA
3	1003	1037	IPOTEKA BANK	RUSTAMOV BEKZOD	32345678910111	AD1111111	111222333	FARGONA	MARGILON	TEST 3	2021	2021-03-01	2024-03-01	CN003	150000000	150000000	19%	86998770	60000000	10:12:03	uy	170000000	305685254	FARGONA QURILISH	IPOTEKA
1	1001	1037	IPOTEKA BANK	ALIYEV AZIZBEK	12345678910111	AD1234567	123456789	TOSHKENT SHAXRI	YAKKASAROY	TEST 1	2023	2023-01-01	2026-01-01	CN001	300000000	300000000	17%	225955323	10000000	10:12:01	uy	350000000	305685252	QURILISH SERVIS	IPOTEKA
\.


--
-- Data for Name: bank_resurs_at_paymentqueue; Type: TABLE DATA; Schema: resurs; Owner: -
--

COPY resurs.bank_resurs_at_paymentqueue (id, credit_id, paid_amount, created_at, sent) FROM stdin;
1	1001	10000000	2026-02-20 09:46:11.072171+05	t
2	1002	20000000	2026-02-20 10:16:55.75784+05	t
3	1002	10000	2026-02-20 10:25:42.200554+05	t
4	1002	10000	2026-02-20 10:25:43.524591+05	t
5	1002	10000	2026-02-20 10:25:44.362325+05	t
6	1002	10000	2026-02-20 10:25:44.659842+05	t
7	1002	10000	2026-02-20 10:25:44.993441+05	t
8	1002	10000	2026-02-20 10:25:45.452803+05	t
9	1002	10000	2026-02-20 10:25:45.658197+05	t
10	1002	10000	2026-02-20 10:25:45.955764+05	t
11	1002	10000	2026-02-20 10:25:46.314649+05	t
12	1002	10000	2026-02-20 10:25:56.000628+05	t
13	1002	10000	2026-02-20 10:25:56.309971+05	t
14	1002	10000	2026-02-20 10:25:56.738426+05	t
15	1002	10000	2026-02-20 10:25:57.060496+05	t
16	1002	10000	2026-02-20 10:25:57.308172+05	t
17	1002	10000	2026-02-20 10:25:57.739138+05	t
18	1003	1000000	2026-02-20 10:38:30.572827+05	t
19	1004	1000000	2026-02-20 10:38:49.285825+05	t
20	1005	1000000	2026-02-20 10:43:37.882545+05	t
21	1003	1000000	2026-02-20 10:59:59.223765+05	t
22	1003	1000000	2026-02-20 11:08:09.759766+05	t
23	1005	1000000	2026-02-20 11:16:13.477751+05	t
24	1005	1000000	2026-02-20 12:33:57.466282+05	t
25	1005	1000000	2026-02-20 12:34:10.038494+05	t
26	1001	30000000	2026-02-20 14:41:26.592552+05	t
27	1001	3000000	2026-02-20 14:48:47.103043+05	t
28	1001	3000000	2026-02-20 14:48:48.878443+05	t
29	1001	3000000	2026-02-20 14:48:49.969118+05	t
30	1001	3000000	2026-02-20 14:48:50.946612+05	t
31	1001	3000000	2026-02-20 14:48:55.212017+05	t
32	1001	3000000	2026-02-20 14:48:56.048465+05	t
33	1001	3000000	2026-02-20 14:48:56.89687+05	t
34	1001	3000000	2026-02-20 14:48:57.691551+05	t
35	1002	1000000	2026-02-20 16:40:37.383458+05	t
36	1002	24000000	2026-02-20 17:32:24.265421+05	t
37	1005	123	2026-02-22 23:46:32.027037+05	t
38	1005	123	2026-02-22 23:46:40.197388+05	t
39	1005	123	2026-02-22 23:46:41.27088+05	t
40	1005	123	2026-02-22 23:46:42.467984+05	t
41	1005	123	2026-02-22 23:46:42.988373+05	t
42	1005	123	2026-02-22 23:46:43.768699+05	t
43	1005	123	2026-02-22 23:46:44.804294+05	t
44	1005	123	2026-02-22 23:46:45.430034+05	t
45	1005	123	2026-02-22 23:46:45.989655+05	t
46	1005	123	2026-02-22 23:46:46.324892+05	t
47	1001	1	2026-02-23 00:45:04.818431+05	t
48	1001	123	2026-02-23 00:58:33.054917+05	t
49	1001	12345	2026-02-23 09:25:11.082984+05	t
50	1001	1234	2026-02-23 09:29:04.817129+05	t
51	1001	12345	2026-02-23 09:29:27.186269+05	t
52	1001	1234	2026-02-23 09:30:26.954467+05	t
53	1001	12345	2026-02-23 09:32:39.365005+05	t
54	1001	123	2026-02-23 09:33:05.30051+05	t
55	1003	123	2026-02-23 09:36:57.060214+05	t
56	1003	123	2026-02-23 09:37:03.024106+05	t
57	1003	123	2026-02-23 09:37:04.208368+05	t
58	1003	123	2026-02-23 09:37:07.162635+05	t
59	1003	123	2026-02-23 09:37:09.528231+05	t
60	1003	123	2026-02-23 09:37:10.835608+05	t
61	1003	123	2026-02-23 09:37:10.994003+05	t
62	1003	123	2026-02-23 09:37:11.169718+05	t
63	1003	123	2026-02-23 09:37:11.44657+05	t
64	1003	123	2026-02-23 09:37:11.51153+05	t
65	1001	123	2026-02-23 10:12:38.941834+05	t
66	1001	1233	2026-02-23 11:10:39.26143+05	t
67	1001	123	2026-02-23 16:51:33.495694+05	t
68	1001	123	2026-02-23 16:51:37.624142+05	t
69	1001	123	2026-02-23 16:51:37.763546+05	t
70	1001	123	2026-02-23 16:51:37.921705+05	t
71	1001	123	2026-02-23 16:51:38.082241+05	t
72	1001	123	2026-02-23 16:51:38.29045+05	t
73	1001	123	2026-02-23 16:51:38.437656+05	t
74	1001	123	2026-02-23 16:51:38.574848+05	t
75	1001	123	2026-02-23 16:51:38.728115+05	t
76	1001	123	2026-02-23 17:30:04.412933+05	t
77	1001	123	2026-02-23 17:30:06.490616+05	t
78	1001	123	2026-02-23 17:30:06.694134+05	t
79	1001	123	2026-02-23 17:30:06.943694+05	t
80	1001	123	2026-02-23 17:30:07.041845+05	t
81	1001	123	2026-02-23 17:30:07.568005+05	t
82	1001	123	2026-02-23 17:30:07.649527+05	t
83	1001	123	2026-02-23 17:30:08.606325+05	t
84	1001	123	2026-02-23 17:30:08.739464+05	t
85	1001	123	2026-02-23 17:30:08.887589+05	t
86	1001	1234	2026-02-24 12:08:56.438088+05	t
\.


--
-- Data for Name: bank_resurs_at_paymentrequestlog; Type: TABLE DATA; Schema: resurs; Owner: -
--

COPY resurs.bank_resurs_at_paymentrequestlog (id, credit_id, paid_amount, response_data, status, created_at) FROM stdin;
1	1001	10000000	{"credit_id": "1001", "paid_amount": "10000000", "credit_balance": "280000000", "loan_paid_date": "2026-02-20 04:46:11", "paid_percent_amount": "10000000"}	201	2026-02-20 09:46:11.088325+05
2	1002	20000000	{"credit_id": "1002", "paid_amount": "20000000", "credit_balance": "130000000", "loan_paid_date": "2026-02-20 05:16:55", "paid_percent_amount": "50000000"}	201	2026-02-20 10:16:55.774832+05
3	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129990000", "loan_paid_date": "2026-02-20 05:25:42", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:42.205889+05
4	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129980000", "loan_paid_date": "2026-02-20 05:25:43", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:43.526393+05
5	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129970000", "loan_paid_date": "2026-02-20 05:25:44", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:44.364856+05
6	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129960000", "loan_paid_date": "2026-02-20 05:25:44", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:44.660923+05
7	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129950000", "loan_paid_date": "2026-02-20 05:25:44", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:44.998897+05
8	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129940000", "loan_paid_date": "2026-02-20 05:25:45", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:45.455137+05
9	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129930000", "loan_paid_date": "2026-02-20 05:25:45", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:45.661197+05
10	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129920000", "loan_paid_date": "2026-02-20 05:25:45", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:45.95859+05
11	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129910000", "loan_paid_date": "2026-02-20 05:25:46", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:46.315609+05
12	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129900000", "loan_paid_date": "2026-02-20 05:25:56", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:56.002677+05
13	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129890000", "loan_paid_date": "2026-02-20 05:25:56", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:56.312484+05
14	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129880000", "loan_paid_date": "2026-02-20 05:25:56", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:56.74107+05
15	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129870000", "loan_paid_date": "2026-02-20 05:25:57", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:57.063008+05
16	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129860000", "loan_paid_date": "2026-02-20 05:25:57", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:57.310856+05
17	1002	10000	{"credit_id": "1002", "paid_amount": "10000", "credit_balance": "129850000", "loan_paid_date": "2026-02-20 05:25:57", "paid_percent_amount": "50000000"}	201	2026-02-20 10:25:57.742625+05
18	1003	1000000	{"credit_id": "1003", "paid_amount": "1000000", "credit_balance": "89000000", "loan_paid_date": "2026-02-20 05:38:30", "paid_percent_amount": "60000000"}	201	2026-02-20 10:38:30.577817+05
19	1004	1000000	{"credit_id": "1004", "paid_amount": "1000000", "credit_balance": "331086944", "loan_paid_date": "2026-02-20 05:38:49", "paid_percent_amount": "1380000"}	201	2026-02-20 10:38:49.289186+05
20	1005	1000000	{"credit_id": "1005", "paid_amount": "1000000", "credit_balance": "59000000", "loan_paid_date": "2026-02-20 05:43:37", "paid_percent_amount": "40000000"}	201	2026-02-20 10:43:37.888657+05
21	1003	1000000	{"credit_id": "1003", "paid_amount": "1000000", "credit_balance": "88000000", "loan_paid_date": "2026-02-20 05:59:59", "paid_percent_amount": "60000000"}	201	2026-02-20 10:59:59.230315+05
22	1003	1000000	{"credit_id": "1003", "paid_amount": "1000000", "credit_balance": "87000000", "loan_paid_date": "2026-02-20 06:08:09", "paid_percent_amount": "60000000"}	201	2026-02-20 11:08:09.763869+05
23	1005	1000000	{"credit_id": "1005", "paid_amount": "1000000", "credit_balance": "58000000", "loan_paid_date": "2026-02-20 06:16:13", "paid_percent_amount": "40000000"}	201	2026-02-20 11:16:13.480748+05
24	1005	1000000	{"credit_id": "1005", "paid_amount": "1000000", "credit_balance": "57000000", "loan_paid_date": "2026-02-20 07:33:57", "paid_percent_amount": "40000000"}	201	2026-02-20 12:33:57.4771+05
25	1005	1000000	{"credit_id": "1005", "paid_amount": "1000000", "credit_balance": "56000000", "loan_paid_date": "2026-02-20 07:34:10", "paid_percent_amount": "40000000"}	201	2026-02-20 12:34:10.040675+05
26	1001	30000000	{"credit_id": "1001", "paid_amount": "30000000", "credit_balance": "250000000", "loan_paid_date": "2026-02-20 09:41:26", "paid_percent_amount": "10000000"}	201	2026-02-20 14:41:26.599587+05
27	1001	3000000	{"credit_id": "1001", "paid_amount": "3000000", "credit_balance": "247000000", "loan_paid_date": "2026-02-20 09:48:47", "paid_percent_amount": "10000000"}	201	2026-02-20 14:48:47.116332+05
28	1001	3000000	{"credit_id": "1001", "paid_amount": "3000000", "credit_balance": "244000000", "loan_paid_date": "2026-02-20 09:48:48", "paid_percent_amount": "10000000"}	201	2026-02-20 14:48:48.880528+05
29	1001	3000000	{"credit_id": "1001", "paid_amount": "3000000", "credit_balance": "241000000", "loan_paid_date": "2026-02-20 09:48:49", "paid_percent_amount": "10000000"}	201	2026-02-20 14:48:49.970974+05
30	1001	3000000	{"credit_id": "1001", "paid_amount": "3000000", "credit_balance": "238000000", "loan_paid_date": "2026-02-20 09:48:50", "paid_percent_amount": "10000000"}	201	2026-02-20 14:48:50.948343+05
31	1001	3000000	{"credit_id": "1001", "paid_amount": "3000000", "credit_balance": "235000000", "loan_paid_date": "2026-02-20 09:48:55", "paid_percent_amount": "10000000"}	201	2026-02-20 14:48:55.213566+05
32	1001	3000000	{"credit_id": "1001", "paid_amount": "3000000", "credit_balance": "232000000", "loan_paid_date": "2026-02-20 09:48:56", "paid_percent_amount": "10000000"}	201	2026-02-20 14:48:56.049466+05
33	1001	3000000	{"credit_id": "1001", "paid_amount": "3000000", "credit_balance": "229000000", "loan_paid_date": "2026-02-20 09:48:56", "paid_percent_amount": "10000000"}	201	2026-02-20 14:48:56.899391+05
34	1001	3000000	{"credit_id": "1001", "paid_amount": "3000000", "credit_balance": "226000000", "loan_paid_date": "2026-02-20 09:48:57", "paid_percent_amount": "10000000"}	201	2026-02-20 14:48:57.693497+05
35	1002	1000000	{"credit_id": "1002", "paid_amount": "1000000", "credit_balance": "128850000", "loan_paid_date": "2026-02-20 11:40:37", "paid_percent_amount": "50000000"}	201	2026-02-20 16:40:37.406452+05
36	1002	24000000	{"credit_id": "1002", "paid_amount": "24000000", "credit_balance": "104850000", "loan_paid_date": "2026-02-20 12:32:24", "paid_percent_amount": "50000000"}	201	2026-02-20 17:32:24.276552+05
37	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55999877", "loan_paid_date": "2026-02-22 18:46:32", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:32.0363+05
38	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55999754", "loan_paid_date": "2026-02-22 18:46:40", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:40.199544+05
39	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55999631", "loan_paid_date": "2026-02-22 18:46:41", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:41.273514+05
40	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55999508", "loan_paid_date": "2026-02-22 18:46:42", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:42.471997+05
41	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55999385", "loan_paid_date": "2026-02-22 18:46:42", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:42.990475+05
42	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55999262", "loan_paid_date": "2026-02-22 18:46:43", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:43.770753+05
43	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55999139", "loan_paid_date": "2026-02-22 18:46:44", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:44.806871+05
44	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55999016", "loan_paid_date": "2026-02-22 18:46:45", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:45.432214+05
45	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55998893", "loan_paid_date": "2026-02-22 18:46:45", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:45.991748+05
46	1005	123	{"credit_id": "1005", "paid_amount": "123", "credit_balance": "55998770", "loan_paid_date": "2026-02-22 18:46:46", "paid_percent_amount": "40000000"}	201	2026-02-22 23:46:46.326352+05
47	1001	1	{"credit_id": "1001", "paid_amount": "1", "credit_balance": "225999999", "loan_paid_date": "2026-02-22 19:45:04", "paid_percent_amount": "10000000"}	201	2026-02-23 00:45:04.829295+05
48	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225999876", "loan_paid_date": "2026-02-22 19:58:33", "paid_percent_amount": "10000000"}	201	2026-02-23 00:58:33.065919+05
49	1001	12345	{"credit_id": "1001", "paid_amount": "12345", "credit_balance": "225987531", "loan_paid_date": "2026-02-23 04:25:11", "paid_percent_amount": "10000000"}	201	2026-02-23 09:25:11.091937+05
50	1001	1234	{"credit_id": "1001", "paid_amount": "1234", "credit_balance": "225986297", "loan_paid_date": "2026-02-23 04:29:04", "paid_percent_amount": "10000000"}	201	2026-02-23 09:29:04.820909+05
51	1001	12345	{"credit_id": "1001", "paid_amount": "12345", "credit_balance": "225973952", "loan_paid_date": "2026-02-23 04:29:27", "paid_percent_amount": "10000000"}	201	2026-02-23 09:29:27.189473+05
52	1001	1234	{"credit_id": "1001", "paid_amount": "1234", "credit_balance": "225972718", "loan_paid_date": "2026-02-23 04:30:26", "paid_percent_amount": "10000000"}	201	2026-02-23 09:30:26.95751+05
53	1001	12345	{"credit_id": "1001", "paid_amount": "12345", "credit_balance": "225960373", "loan_paid_date": "2026-02-23 04:32:39", "paid_percent_amount": "10000000"}	201	2026-02-23 09:32:39.368997+05
54	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225960250", "loan_paid_date": "2026-02-23 04:33:05", "paid_percent_amount": "10000000"}	201	2026-02-23 09:33:05.304303+05
55	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86999877", "loan_paid_date": "2026-02-23 04:36:57", "paid_percent_amount": "60000000"}	201	2026-02-23 09:36:57.064217+05
56	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86999754", "loan_paid_date": "2026-02-23 04:37:03", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:03.026703+05
57	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86999631", "loan_paid_date": "2026-02-23 04:37:04", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:04.212044+05
58	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86999508", "loan_paid_date": "2026-02-23 04:37:07", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:07.16674+05
59	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86999385", "loan_paid_date": "2026-02-23 04:37:09", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:09.53124+05
60	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86999262", "loan_paid_date": "2026-02-23 04:37:10", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:10.838384+05
61	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86999139", "loan_paid_date": "2026-02-23 04:37:10", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:10.99706+05
62	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86999016", "loan_paid_date": "2026-02-23 04:37:11", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:11.17265+05
63	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86998893", "loan_paid_date": "2026-02-23 04:37:11", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:11.450562+05
64	1003	123	{"credit_id": "1003", "paid_amount": "123", "credit_balance": "86998770", "loan_paid_date": "2026-02-23 04:37:11", "paid_percent_amount": "60000000"}	201	2026-02-23 09:37:11.514291+05
65	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225960127", "loan_paid_date": "2026-02-23 05:12:38", "paid_percent_amount": "10000000"}	201	2026-02-23 10:12:38.949834+05
66	1001	1233	{"credit_id": "1001", "paid_amount": "1233", "credit_balance": "225958894", "loan_paid_date": "2026-02-23 06:10:39", "paid_percent_amount": "10000000"}	201	2026-02-23 11:10:39.293368+05
67	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225958771", "loan_paid_date": "2026-02-23 11:51:33", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:33.501857+05
68	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225958648", "loan_paid_date": "2026-02-23 11:51:37", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:37.627009+05
69	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225958525", "loan_paid_date": "2026-02-23 11:51:37", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:37.764549+05
70	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225958402", "loan_paid_date": "2026-02-23 11:51:37", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:37.923381+05
71	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225958279", "loan_paid_date": "2026-02-23 11:51:38", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:38.084273+05
72	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225958156", "loan_paid_date": "2026-02-23 11:51:38", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:38.292964+05
73	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225958033", "loan_paid_date": "2026-02-23 11:51:38", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:38.4396+05
74	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225957910", "loan_paid_date": "2026-02-23 11:51:38", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:38.57613+05
75	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225957787", "loan_paid_date": "2026-02-23 11:51:38", "paid_percent_amount": "10000000"}	201	2026-02-23 16:51:38.730116+05
76	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225957664", "loan_paid_date": "2026-02-23 12:30:04", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:04.420958+05
77	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225957541", "loan_paid_date": "2026-02-23 12:30:06", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:06.490616+05
78	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225957418", "loan_paid_date": "2026-02-23 12:30:06", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:06.695642+05
79	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225957295", "loan_paid_date": "2026-02-23 12:30:06", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:06.944201+05
80	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225957172", "loan_paid_date": "2026-02-23 12:30:07", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:07.041845+05
81	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225957049", "loan_paid_date": "2026-02-23 12:30:07", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:07.576141+05
82	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225956926", "loan_paid_date": "2026-02-23 12:30:07", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:07.649527+05
83	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225956803", "loan_paid_date": "2026-02-23 12:30:08", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:08.61006+05
84	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225956680", "loan_paid_date": "2026-02-23 12:30:08", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:08.743806+05
85	1001	123	{"credit_id": "1001", "paid_amount": "123", "credit_balance": "225956557", "loan_paid_date": "2026-02-23 12:30:08", "paid_percent_amount": "10000000"}	201	2026-02-23 17:30:08.887589+05
86	1001	1234	{"credit_id": "1001", "paid_amount": "1234", "credit_balance": "225955323", "loan_paid_date": "2026-02-24 07:08:56", "paid_percent_amount": "10000000"}	201	2026-02-24 12:08:56.441648+05
\.


--
-- Data for Name: bank_resurs_at_resursrequestlog; Type: TABLE DATA; Schema: resurs; Owner: -
--

COPY resurs.bank_resurs_at_resursrequestlog (id, credit_id, pnfl, status, created_at) FROM stdin;
1	1001	12345678910111	200	2026-02-19 15:34:29.432485+05
2	1002	22345678910111	200	2026-02-19 17:18:40.819358+05
3	1001	12345678910111	200	2026-02-20 11:09:24.49439+05
4	1001	12345678910111	200	2026-02-20 11:11:33.666924+05
5	1001	12345678910111	200	2026-02-20 11:11:42.175914+05
6	1001	12345678910111	200	2026-02-20 11:11:55.286733+05
7	1001	12345678910111	200	2026-02-20 11:24:45.091998+05
8	10232401	12345678910232	204	2026-02-20 11:25:13.023399+05
9	1001	12345678910111	200	2026-02-20 12:18:38.42945+05
10	1001	12345678910111	200	2026-02-20 12:19:53.474252+05
11	1001	12345678910111	200	2026-02-20 12:37:35.395763+05
12	1001	12345678910111	200	2026-02-20 14:26:44.795907+05
13	1001	12345678910111	200	2026-02-20 14:33:17.721932+05
14	1001	12345678910111	200	2026-02-20 14:43:08.328197+05
15	1001	12345678910111	200	2026-02-20 14:56:29.101949+05
16	1001	12345678910111	200	2026-02-20 14:56:32.498852+05
17	1001	12345678910111	200	2026-02-20 14:56:33.498996+05
18	1001	12345678910111	200	2026-02-20 14:56:34.329515+05
19	1001	12345678910111	200	2026-02-20 14:56:35.246266+05
20	1001	12345678910111	200	2026-02-20 14:56:36.111076+05
21	1001	12345678910111	200	2026-02-20 14:56:36.957152+05
22	1001	12345678910111	200	2026-02-20 14:56:37.637855+05
23	1001	12345678910111	200	2026-02-20 14:56:38.379045+05
24	1001	12345678910111	200	2026-02-20 14:56:39.127353+05
25	1001	12345678910111	200	2026-02-20 16:46:22.694303+05
26	1001	12345678910111	200	2026-02-20 17:27:53.482044+05
27	1001		400	2026-02-20 17:28:14.62057+05
28	1001		400	2026-02-20 17:28:50.806962+05
29	1001	12345678910111	200	2026-02-20 17:29:30.316484+05
30	1001	12345678910111	200	2026-02-20 17:38:03.410436+05
31	1001	12345678910111	200	2026-02-20 17:39:46.685347+05
32	1001	1234578910111	204	2026-02-20 17:41:40.87413+05
33	1001	1234578910111	204	2026-02-20 17:41:42.443083+05
34	1001	12345678910111	200	2026-02-20 17:45:21.382275+05
35	1001	12345678910111	200	2026-02-22 23:25:46.494692+05
36	1001	12345678910111	200	2026-02-23 00:20:15.552053+05
37	1001		400	2026-02-23 00:20:30.489099+05
38	100		400	2026-02-23 00:28:14.554273+05
39	100	123	204	2026-02-23 00:28:20.324465+05
40	100	123	204	2026-02-23 00:28:21.760219+05
41	100	123	204	2026-02-23 00:28:22.516352+05
42	100	123	204	2026-02-23 00:28:23.544121+05
43	100	123	204	2026-02-23 00:28:23.771687+05
44	100	123	204	2026-02-23 00:28:25.560577+05
45	100	123	204	2026-02-23 00:28:25.764661+05
46	100	123	204	2026-02-23 00:28:25.919781+05
47	100	123	204	2026-02-23 00:28:26.189023+05
48	1001	12345678910111	200	2026-02-23 00:30:01.520805+05
49	1001	12345678910111	200	2026-02-23 00:31:40.006012+05
50	1001	12345678910111	200	2026-02-23 00:34:30.478323+05
51	1001	12345678910111	200	2026-02-23 00:35:39.225146+05
52	1001	12345678910111	200	2026-02-23 00:35:55.195888+05
53	1001	12345678910111	200	2026-02-23 00:42:15.313526+05
54	1001	12345678910111	200	2026-02-23 09:06:16.252333+05
55	1001	12345678910111	200	2026-02-23 09:07:05.182252+05
56	1001	123456789910111	400	2026-02-23 09:15:05.034524+05
57	1001	123456789910111	400	2026-02-23 09:15:27.742347+05
58	1001	12345678910111	200	2026-02-23 09:16:20.862846+05
59	1001	123456678910111	400	2026-02-23 09:20:15.856286+05
60	1001	12345678910111	200	2026-02-23 09:24:55.533914+05
61	1001	12345678910111	200	2026-02-23 09:28:20.569542+05
62	1001	12345678910111	200	2026-02-23 09:37:59.33105+05
63	1001	12345678910111	200	2026-02-23 10:11:52.260911+05
64	1001	12345678910111	200	2026-02-23 10:17:19.478131+05
65	1001	12345678910111	200	2026-02-23 10:18:36.313753+05
66	1001	12345678910111	200	2026-02-23 10:18:57.27897+05
67	1001		400	2026-02-23 11:33:57.580473+05
68	1001	12345678910111	200	2026-02-23 11:34:12.241629+05
69	1001	12345678910111	200	2026-02-23 16:51:18.553994+05
70	1001	12345678910111	200	2026-02-24 12:02:09.525327+05
71	1001	12345678910111	200	2026-02-24 12:10:08.09162+05
\.


--
-- Name: bank_resurs_at_creditdata_id_seq; Type: SEQUENCE SET; Schema: resurs; Owner: -
--

SELECT pg_catalog.setval('resurs.bank_resurs_at_creditdata_id_seq', 5, true);


--
-- Name: bank_resurs_at_paymentqueue_id_seq; Type: SEQUENCE SET; Schema: resurs; Owner: -
--

SELECT pg_catalog.setval('resurs.bank_resurs_at_paymentqueue_id_seq', 86, true);


--
-- Name: bank_resurs_at_paymentrequestlog_id_seq; Type: SEQUENCE SET; Schema: resurs; Owner: -
--

SELECT pg_catalog.setval('resurs.bank_resurs_at_paymentrequestlog_id_seq', 86, true);


--
-- Name: bank_resurs_at_resursrequestlog_id_seq; Type: SEQUENCE SET; Schema: resurs; Owner: -
--

SELECT pg_catalog.setval('resurs.bank_resurs_at_resursrequestlog_id_seq', 71, true);


--
-- Name: bank_resurs_at_creditdata bank_resurs_at_creditdata_credit_id_key; Type: CONSTRAINT; Schema: resurs; Owner: -
--

ALTER TABLE ONLY resurs.bank_resurs_at_creditdata
    ADD CONSTRAINT bank_resurs_at_creditdata_credit_id_key UNIQUE (credit_id);


--
-- Name: bank_resurs_at_creditdata bank_resurs_at_creditdata_pkey; Type: CONSTRAINT; Schema: resurs; Owner: -
--

ALTER TABLE ONLY resurs.bank_resurs_at_creditdata
    ADD CONSTRAINT bank_resurs_at_creditdata_pkey PRIMARY KEY (id);


--
-- Name: bank_resurs_at_paymentqueue bank_resurs_at_paymentqueue_pkey; Type: CONSTRAINT; Schema: resurs; Owner: -
--

ALTER TABLE ONLY resurs.bank_resurs_at_paymentqueue
    ADD CONSTRAINT bank_resurs_at_paymentqueue_pkey PRIMARY KEY (id);


--
-- Name: bank_resurs_at_paymentrequestlog bank_resurs_at_paymentrequestlog_pkey; Type: CONSTRAINT; Schema: resurs; Owner: -
--

ALTER TABLE ONLY resurs.bank_resurs_at_paymentrequestlog
    ADD CONSTRAINT bank_resurs_at_paymentrequestlog_pkey PRIMARY KEY (id);


--
-- Name: bank_resurs_at_resursrequestlog bank_resurs_at_resursrequestlog_pkey; Type: CONSTRAINT; Schema: resurs; Owner: -
--

ALTER TABLE ONLY resurs.bank_resurs_at_resursrequestlog
    ADD CONSTRAINT bank_resurs_at_resursrequestlog_pkey PRIMARY KEY (id);


--
-- Name: bank_resurs_at_creditdata_credit_id_85fc7532_like; Type: INDEX; Schema: resurs; Owner: -
--

CREATE INDEX bank_resurs_at_creditdata_credit_id_85fc7532_like ON resurs.bank_resurs_at_creditdata USING btree (credit_id varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

\unrestrict LQe4KSNQmZ8kW9G3agbm0S86oCROfcVbpYekolNPhAm876jL2oDGlvFkBgQb4W2

