# Generated by Django 6.0.1 on 2026-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('credit_id', models.CharField(blank=True, max_length=50, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('response_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.CharField(max_length=10, unique=True)),
                ('bank_mfo', models.IntegerField()),
                ('bank_name', models.CharField(max_length=150)),
                ('loan_person_name', models.CharField(max_length=150)),
                ('loan_pnfl', models.CharField(max_length=14)),
                ('pas_series_number', models.CharField(max_length=9)),
                ('tin', models.IntegerField()),
                ('region', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('date_of_contract', models.CharField(max_length=10)),
                ('loan_allocated_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('contract_number', models.CharField(max_length=10)),
                ('contract_summ', models.CharField(max_length=20)),
                ('disbursed_loan_amount', models.CharField(max_length=20)),
                ('loan_interest_rate', models.CharField(max_length=2)),
                ('credit_balance', models.CharField(max_length=20)),
                ('paid_precent_amount', models.CharField(max_length=20)),
                ('cadastral_number', models.CharField(max_length=30)),
                ('type_of_supply', models.CharField(max_length=150)),
                ('credit_provision_amount', models.CharField(max_length=150)),
                ('tin_of_company', models.CharField(max_length=9)),
                ('name_of_company', models.CharField(max_length=150)),
                ('type_of_credit', models.CharField(max_length=150)),
            ],
        ),
    ]
