# Generated by Django 6.0.1 on 2026-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_at', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAtResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.CharField(max_length=20)),
                ('response_data', models.JSONField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ApiRequestLog',
        ),
        migrations.DeleteModel(
            name='CreditData',
        ),
    ]
