# Generated by Django 6.0.1 on 2026-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_at', '0002_bankatresponselog_delete_apirequestlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankatresponselog',
            name='credit_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankatresponselog',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
