# Generated by Django 6.0.1 on 2026-02-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_at', '0003_alter_bankatresponselog_credit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInfoUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
