# Generated by Django 6.0.1 on 2026-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_resurs_at', '0002_resursrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resursrequestlog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
