# Generated by Django 6.0.1 on 2026-02-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_resurs_at', '0003_alter_resursrequestlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.CharField(max_length=20)),
                ('paid_amount', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
