# Generated by Django 6.0.1 on 2026-02-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_resurs_at', '0004_paymentqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.CharField(max_length=20)),
                ('paid_amount', models.CharField(max_length=20)),
                ('response_data', models.JSONField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
